# Generated by Django 2.0 on 2017-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmae', models.TextField(default='')),
                ('cover', models.ImageField(null=True, upload_to='img_products/', verbose_name='Обложка товара')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть?')),
            ],
            options={
                'verbose_name': 'Наш товар',
                'verbose_name_plural': 'Наши товары',
            },
        ),
    ]
