# Generated by Django 2.0 on 2017-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='nmae',
        ),
        migrations.AddField(
            model_name='products',
            name='desk',
            field=models.TextField(default='', verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название товара'),
        ),
    ]
