# Generated by Django 2.0 on 2017-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, max_length=255, verbose_name='Цена'),
        ),
    ]
