# Generated by Django 2.0 on 2017-12-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20171228_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='base_photo',
            field=models.CharField(default='/static/avatar/avatar-1.png', max_length=255, verbose_name='Аватар по умолчанию'),
        ),
    ]
