# Generated by Django 2.0 on 2018-01-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile_base_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-pk'], 'verbose_name': 'Профиль юзера', 'verbose_name_plural': 'Профили юзеров'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='base_photo',
            field=models.CharField(default='avatar-1.png', max_length=255, verbose_name='Аватар по умолчанию'),
        ),
    ]
